In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('Marketing_Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)

[[ 84.72  19.2   48.96]
 [351.48  33.96  51.84]
 [135.48  20.88  46.32]
 [116.64   1.8   36.  ]
 [318.72  24.     0.36]
 [114.84   1.68   8.88]
 [348.84   4.92  10.2 ]
 [320.28  52.56   6.  ]
 [ 89.64  59.28  54.84]
 [ 51.72  32.04  42.12]
 [273.6   45.24  38.4 ]
 [243.    26.76  37.92]
 [212.4   40.08  46.44]
 [352.32  33.24   2.16]
 [248.28  10.08  31.68]
 [ 30.12  30.84  51.96]
 [210.12  27.    37.8 ]
 [107.64  11.88  42.84]
 [287.88  49.8   22.2 ]
 [272.64  18.96  59.88]
 [ 80.28  14.04  44.16]
 [239.76   3.72  41.52]
 [120.48  11.52   4.32]
 [259.68  50.04  47.52]
 [219.12  55.44  70.44]
 [315.24  34.56  19.08]
 [238.68  59.28  72.  ]
 [  8.76  33.72  49.68]
 [163.44  23.04  19.92]
 [252.96  59.52  45.24]
 [252.84  35.4   11.16]
 [ 64.2    2.4   25.68]
 [313.56  51.24  65.64]
 [287.16  18.6   32.76]
 [123.24  35.52  10.08]
 [157.32  51.36  34.68]
 [ 82.8   11.16   1.08]
 [ 37.8   29.52   2.64]
 [167.16  17.4   12.24]
 [284.88  33.    13.2 ]
 [260.16  52.68  32.64]
 [238.92  36.72 

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [5]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [6]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[17.48 16.32]
 [16.37 13.8 ]
 [23.03 23.28]
 [24.76 26.04]
 [18.44 18.72]
 [ 9.89 11.64]
 [27.58 30.48]
 [28.88 31.44]
 [23.06 23.52]
 [19.06 19.08]
 [13.22  9.6 ]
 [14.35 14.04]
 [ 9.24 11.4 ]
 [13.14  7.92]
 [10.24 11.88]
 [16.25 13.92]
 [20.01 18.84]
 [25.73 27.84]
 [12.05 13.44]
 [13.89 14.16]
 [19.72 20.28]
 [10.95 11.4 ]
 [22.23 20.88]
 [27.71 30.48]
 [20.47 20.04]
 [11.95 11.52]
 [19.47 19.92]
 [15.99 14.64]
 [23.27 24.84]
 [20.34 20.76]
 [25.56 28.44]
 [18.45 18.24]
 [ 6.66  3.84]
 [20.58 20.4 ]
 [18.95 17.64]]
